/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.resource.server)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

group = "org.programming.techie.microservice-1"
description = "microservice-1"
